doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Shared:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Shared/Domain/Entity'
                prefix: 'App\Shared\Domain\Entity'
                alias: Shared
            Satellite:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Satellite/Domain/Entity'
                prefix: 'App\Satellite\Domain\Entity'
                alias: Satellite
            Todo:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Todo/Domain/Entity'
                prefix: 'App\Todo\Domain\Entity'
                alias: Todo
            User:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: User
when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
