symfonycasts_sass:
    root_sass:
      - '%kernel.project_dir%/assets/styles/app.scss'
      - '%kernel.project_dir%/assets/styles/todo.scss'
      - '%kernel.project_dir%/assets/styles/footer.scss'
      - '%kernel.project_dir%/assets/styles/header.scss'
      - '%kernel.project_dir%/assets/styles/lucky.scss'
      - '%kernel.project_dir%/assets/styles/weather.scss'
