version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: workbench-app
    restart: always
    depends_on:
      - db
      - mailhog
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - /etc/localtime:/etc/localtime:ro
    networks:
      - workbench-network
    ports:
      - "8001:80"

  db:
    image: mysql:9
    restart: always
    container_name: workbench-mysql
    command:
      - --innodb-buffer-pool-size=512M
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: workbench
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    ports:
      - '3301:3306'
    networks:
      - workbench-network

  mailhog:
    image: mailhog/mailhog
    container_name: workbench-mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - workbench-network

networks:
  workbench-network:
    name: docker_default
    external: true
